// Mocks generated by Mockito 5.0.16 from annotations
// in framework_challenge/test/features/fruit_shop/infra/services/print_cart_invoice_service_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:framework_challenge/features/fruit_shop/infra/datasources/print_cart_invoice_data_source.dart'
    as _i2;
import 'package:framework_challenge/features/fruit_shop/infra/models/cart_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [CartInvoiceDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartInvoiceDataSource extends _i1.Mock
    implements _i2.CartInvoiceDataSource {
  MockCartInvoiceDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call({_i4.CartModel? cart}) =>
      (super.noSuchMethod(Invocation.method(#call, [], {#cart: cart}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}
